name: flutter_lib
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #添加网络请求依赖
  http: ^0.11.3+16
  dio : 3.0.9
  # provider
  provider: 4.0.0
  # 添加sharedPreference依赖
  shared_preferences: ^0.5.0
  # json解析
  json_serializable: ^3.0.0
  build_runner: ^1.6.1
  # 添加文件依赖
  path_provider: ^1.6.9
  #添加Sqflite依赖
  sqflite: ^1.0.0
  cupertino_icons: ^0.1.2
  #依赖本地flutter_uni项目
  flutter_uni:
    path: ../flutter_uni
  flutter_channel:
    path: ../flutter_channel
  yc_flutter_utils:
    path: ../flutter_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/map_marker_b.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.png
  module:
    androidPackage: com.example.flutter_lib
    iosBundleIdentifier: com.example.flutterLib
